AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-dynamic-sample

  Sample SAM Template for cognito-dynamic-sample

Globals:
  Function:
    Timeout: 3

Resources:
  ReadUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./get-user/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /user
            Method: GET

  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:ap-northeast-1:xxxxxxx:userpool/xxxxxxxx
            AuthType: COGNITO_USER_POOLS
            CognitoAuthorizationIdentity:
              Header: Aurhorization
        DefaultAuthorizer: CognitoAuthorizer
        InvokeRole: CALLER_CREDENTIALS
        AddDefaultAuthorizerToCorsPreflight: false
        ApiKeyRequired: false
        ResourcePolicy:
          CustomStatements: [ {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "execute-api:/Prod/*",
          } ]
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Sample Hello API
          version: 1.0.0
        schemes:
          - https
        paths:
          /user:
            get:
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                uri: !Join [ '' , [ 'arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/' , !GetAtt  ReadUserFunction.Arn , '/invocations' ] ]
                passthroughBehavior: when_no_templates
                httpMethod: POST
                type: aws_proxy


Outputs:
  ReadUserFunction:
    Description: "Get User Function ARN"
    Value: !GetAtt ReadUserFunction.Arn
  ReadUserFunctionIamRole:
    Description: "Implicit IAM Role created for Get User function"
    Value: !GetAtt ReadUserFunctionRole.Arn
